version: '3'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
